SELECT * FROM retail.sales;
#1 List all distinct product categories available in the dataset.
SELECT DISTINCT s.`Product Category`
FROM sales s;

#2 Find the total number of transactions in the dataset.
select count(*) as Total_Transactions from sales;

#3 Retrieve all transactions where the Total Amount is greater than 500.

select s.`Transaction ID`,s.`Customer ID`,s.`Total Amount` from sales s 
where s.`Total Amount` >500;

#4 Count how many customers are Male and Female.

select s.Gender, count(*) as count from sales s group by s.Gender;

#5 Calculate the total revenue generated from each product category.
select s.`Product Category` ,sum(s.`Total Amount`) as Total_Revenue from sales s group by s.`Product Category`;

#6 Find the top 5 highest-value transactions.
select * from sales s order by s.`Total Amount` desc limit 5;

#7 Calculate the average age of customers by gender.
select s.Gender,avg(s.Age) as avg_age from sales s 
group by s.Gender;

#8 Identify which customer has made the highest total purchase amount.

select s.`Customer ID` ,sum(s.`Total Amount`) as Total_spent from sales s 
group by s.`Customer ID`
order by Total_spent desc limit 1;

#9 Show the total quantity sold for each product category.
select s.`Product Category`, sum(s.Quantity) as Total_quantity from sales s
group by s.`Product Category`;

#10 Retrieve all transactions that occurred in the month of May.

select * from sales where month(date)=5;

#11 Find the minimum, maximum, and average Total Amount.
select MIN(s.`Total Amount`) as minimum ,
MAX(s.`Total Amount`) as maximum,
avg(s.`Total Amount`) as average
from sales s;

#12 Count how many customers are in each age group (e.g., <20, 20–40, 40–60, >60)
SELECT 
    CASE
        WHEN Age < 20 THEN 'Below 20'
        WHEN Age BETWEEN 20 AND 40 THEN '20-40'
        WHEN Age BETWEEN 40 AND 60 THEN '40-60'
        ELSE 'Above 60'
    END AS Age_Group,
    COUNT(*) AS Count
FROM sales
GROUP BY Age_Group;

#13 Show the total sales revenue for each month of the year.
 select month(date) as month, sum(s.`Total Amount`) as Total_Revenue from sales s
 group by month(date) order by month;
 
#14 Identify the product category with the highest average selling price.

select s.`Product Category`, avg(s.`Price per Unit`) as avg_price from sales s
group by s.`Product Category` order by avg_price desc;

#15 Retrieve all transactions where quantity purchased is more than 2.
 select * from sales s where s.Quantity >2;
 
 #16 Find the most frequently purchased product category.
 select s.`Product Category`, count(*) as frequncy
 from sales s  group by s.`Product Category` order by frequncy desc limit 1;
 
 #17 Calculate total revenue generated by each gender.
 select s.Gender, sum(s.`Total Amount`) as Total_Revenue from sales s
 group by s.Gender order by Total_Revenue;
 
 #18 Show the number of transactions done by each customer.
 select s.`Customer ID`,count(*) as Trans from sales s group by s.`Customer ID`;
 
 
 #19 Customers who made transactions > 1000.
 select * from sales s where s.`Total Amount` >1000;
 
 #20 Transactions sorted by date (newest first).
 select * from sales s
 order by date desc;